# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_played',
            field=models.CharField(default='01/01/2000', max_length=12),
        ),
    ]
